USE panel_hogares2;

DROP TABLE IF EXISTS tbl_IDEN2016;

CREATE TABLE tbl_IDEN2016(
	IDENPER NUMERIC(11) DEFAULT NULL,
	IDENHOG NUMERIC(11) DEFAULT NULL,
	CCAA CHAR(2) DEFAULT NULL,
	CPRO CHAR(2) DEFAULT NULL,
	CMUN CHAR(3) DEFAULT NULL,
	TIPOHOG CHAR(5) DEFAULT NULL,
	TRAMO CHAR(1) DEFAULT NULL,
	FACTORCAL NUMERIC(20,10) DEFAULT NULL,
	FACTORCALNACI NUMERIC(20,10) DEFAULT NULL,
	FACTORDIS NUMERIC(20,10) DEFAULT NULL,
	FACTORDISNACI NUMERIC(20,10) DEFAULT NULL,
	NACIO CHAR(3) DEFAULT NULL,
	TIPCONTRIB CHAR(2) DEFAULT NULL,
	IDENPERS_CONY NUMERIC(11) DEFAULT NULL,
	SECCION CHAR(10) DEFAULT NULL
) engine=columnstore CHARSET=latin1 COLLATE=latin1_spanish_ci;